### ISSUE TITLE
Include `LICENSE` file in PyPI source

### ISSUE THREAD

**Issue by sugatoray** [stephenleo/stripnet#2]
The PyPI source does not have any LICENSE file as of `v0.0.5`. Please add it.

> You need to add a `MENIFEST.in` file and add the following line to it.

```sh
include LICENSE
```

Or, you could modify setup.py file as follows:

```python
setup(
	...
	license_files=("LICENSE",),
	...
)
```

Anyone of those should fix this issue.

**Comment by sugatoray** [comment]
cc: @stephenleo

**Comment by stephenleo** [comment]
Thank you for the finding and suggestion! pushed a new version that fixes this.
