### ISSUE TITLE
Add a conda install option

### ISSUE THREAD

**Issue by sugatoray** [stephenleo/stripnet#4]
Recently I worked on adding `stripnet` from PyPI to conda-forge. Now you can install stripnet as:

```sh
conda install -c conda-forge stripnet
```

- Conda-forge PR: https://github.com/conda-forge/staged-recipes/pull/17460#issuecomment-1015238924
- The conda-forge feedstock (for maintaining stripnet on conda-forge): https://github.com/conda-forge/stripnet-feedstock

:bulb: I will push a PR to update the readme with the conda install option.

**Comment by stephenleo** [comment]
This is awesome! Thanks so much.
